"""
Lead intake logic — processes bookings, referral emails, and forwarded leads.
Shared by webhook_intake.py (HTTP payloads) and bot.py (Telegram messages).
"""

import json
import logging
import os
from datetime import datetime

from openai import OpenAI

import db
from branding import build_advisor_intro, build_anti_injection_warning, get_prompt_context

logger = logging.getLogger(__name__)

client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY", ""))


def process_booking(data: dict) -> str:
    """Process an Outlook Bookings payload from Power Automate."""
    name = (data.get("name") or "").strip()
    if not name:
        return "No name in booking payload."

    email = data.get("email", "")
    phone = data.get("phone", "")
    service = data.get("service", "")
    start_time = data.get("start_time", "")
    notes = data.get("notes", "")

    booking_notes = f"Booked: {service}" if service else "Booked via Outlook"
    if notes:
        booking_notes += f" | {notes}"

    # Dedup: try email first, then phone, then fall back to name
    existing = None
    if email:
        existing = db.get_prospect_by_email(email)
    if not existing and phone:
        existing = db.get_prospect_by_phone(phone)
    if not existing:
        existing = db.get_prospect_by_name(name)
    if existing:
        old_notes = existing.get("notes", "")
        combined = f"{old_notes} | [Booking] {booking_notes}" if old_notes else f"[Booking] {booking_notes}"
        updates = {"notes": combined}
        if email and not existing.get("email"):
            updates["email"] = email
        if phone and not existing.get("phone"):
            updates["phone"] = phone
        db.update_prospect(existing["name"], updates)

        if start_time:
            meeting_date, meeting_time = _parse_datetime(start_time)
            db.add_meeting({
                "date": meeting_date, "time": meeting_time,
                "prospect": existing["name"], "type": service or "Consultation",
                "prep_notes": booking_notes,
            })

        db.add_interaction({
            "prospect": existing["name"], "source": "outlook_booking",
            "raw_text": json.dumps(data), "summary": booking_notes,
        })
    else:
        db.add_prospect({
            "name": name, "email": email, "phone": phone,
            "source": "Outlook Booking", "stage": "New Lead",
            "priority": "Warm", "product": _guess_product(service, notes),
            "notes": booking_notes,
        })

        if start_time:
            meeting_date, meeting_time = _parse_datetime(start_time)
            db.add_meeting({
                "date": meeting_date, "time": meeting_time,
                "prospect": name, "type": service or "Consultation",
                "prep_notes": booking_notes,
            })

        db.add_interaction({
            "prospect": name, "source": "outlook_booking",
            "raw_text": json.dumps(data), "summary": booking_notes,
        })
        db.add_activity({
            "prospect": name, "action": "Outlook Booking received",
            "outcome": booking_notes, "next_step": "Prepare for meeting",
        })
        _score_and_schedule(name)

    # Extract client intelligence
    try:
        import memory_engine
        prospect_obj = db.get_prospect_by_name(data.get("name", ""))
        if prospect_obj:
            memory_engine.extract_facts_from_interaction(
                prospect_name=prospect_obj["name"],
                prospect_id=prospect_obj["id"],
                interaction_text=f"Booking: {data.get('service', '')}. Notes: {data.get('notes', '')}",
                source="booking",
            )
    except Exception:
        logger.exception("Memory extraction failed for booking (non-blocking)")

    meeting_date = data.get("start_time", "")[:10] if data.get("start_time") else ""
    meeting_time_str = ""
    if data.get("start_time") and "T" in data["start_time"]:
        meeting_time_str = data["start_time"].split("T")[1][:5]

    # Log that meeting prep will be auto-generated by the scheduler
    try:
        prospect_display = data.get("name", "Unknown")
        is_new = "NEW prospect" if not existing else "existing prospect"
        service_name = data.get("service", "Meeting")

        if meeting_date:
            logger.info(
                "Booking for %s (%s) on %s at %s — meeting prep will be auto-generated",
                prospect_display, is_new, meeting_date, meeting_time_str,
            )
    except Exception:
        logger.exception("Booking prep logging failed (non-blocking)")

    # Trigger pre-call iMessage nurture sequence
    try:
        prospect_obj = db.get_prospect_by_name(name)
        _phone = (prospect_obj or {}).get("phone", "") or phone
        if _phone and data.get("start_time"):
            import booking_nurture
            booking_nurture.create_sequence(
                prospect_name=name,
                prospect_id=prospect_obj["id"] if prospect_obj else None,
                phone=_phone,
                meeting_datetime_str=data["start_time"],
                meeting_date=meeting_date,
                meeting_time=meeting_time_str,
                meeting_type=data.get("service", "Consultation"),
                product=(prospect_obj or {}).get("product", ""),
            )
    except Exception:
        logger.exception("Booking nurture sequence creation failed (non-blocking)")

    if not existing:
        return f"New prospect: {name} — {booking_notes}. Meeting added."
    else:
        return f"Updated {existing['name']} with new booking. Meeting added."


def process_calendar_event(data: dict) -> str:
    """Process an Outlook calendar event from Power Automate.

    Handles multiple attendees, location, categories, and meeting type detection.
    Expected data fields:
      subject, start_time, end_time, location, body, categories,
      attendees: [{"name": "...", "email": "..."}]
      is_online (bool), online_meeting_url
    """
    subject = (data.get("subject") or "").strip()
    if not subject:
        return "No subject in calendar event."

    attendees = data.get("attendees") or []
    # If attendees came as a single dict (one attendee), wrap it
    if isinstance(attendees, dict):
        attendees = [attendees]

    start_time = data.get("start_time") or data.get("date") or ""
    end_time = data.get("end_time") or ""
    location = data.get("location") or ""
    body = data.get("body") or data.get("notes") or ""
    categories = data.get("categories") or ""
    is_online = data.get("is_online", False)
    online_url = data.get("online_meeting_url") or ""

    # Build meeting context
    meeting_type = _classify_meeting(subject, location, is_online)
    meeting_details = f"{meeting_type}: {subject}"
    if location:
        meeting_details += f" @ {location}"
    if is_online and online_url:
        meeting_details += " (virtual)"
    if body:
        meeting_details += f" | {body[:200]}"

    results = []

    if not attendees:
        # No attendees — just log the meeting for Marc's schedule
        if start_time:
            meeting_date, meeting_time = _parse_datetime(start_time)
            db.add_meeting({
                "date": meeting_date, "time": meeting_time,
                "prospect": "", "type": meeting_type,
                "prep_notes": meeting_details,
            })
        results.append(f"Calendar event logged: {subject}")
    else:
        # Look up the advisor's own email so we can skip them in attendee list
        owner_email = ""
        try:
            with db.get_db() as _conn:
                _owner = _conn.execute(
                    "SELECT email FROM users WHERE role = 'owner' AND tenant_id = %s LIMIT 1",
                    (db._current_tenant_id.get(1),)
                ).fetchone()
                if _owner:
                    owner_email = (_owner["email"] or "").lower()
        except Exception:
            pass

        for att in attendees:
            att_name = (att.get("name") or "").strip()
            att_email = (att.get("email") or "").strip()

            if not att_name and not att_email:
                continue
            if not att_name:
                att_name = att_email.split("@")[0].replace(".", " ").title()

            # Skip the advisor's own email (tenant owner)
            if owner_email and att_email.lower() == owner_email:
                continue

            existing = db.get_prospect_by_name(att_name)
            if existing:
                old_notes = existing.get("notes", "")
                combined = f"{old_notes} | [Calendar] {meeting_details}" if old_notes else f"[Calendar] {meeting_details}"
                updates = {"notes": combined}
                if att_email and not existing.get("email"):
                    updates["email"] = att_email
                db.update_prospect(existing["name"], updates)
                action = f"Updated {existing['name']}"
            else:
                product = _guess_product(subject, body)
                db.add_prospect({
                    "name": att_name, "email": att_email, "phone": "",
                    "source": "Calendar Event", "stage": "New Lead",
                    "priority": "Warm", "product": product,
                    "notes": f"[Calendar] {meeting_details}",
                })
                _score_and_schedule(att_name)
                action = f"New prospect: {att_name}"

            # Add meeting entry
            if start_time:
                meeting_date, meeting_time = _parse_datetime(start_time)
                db.add_meeting({
                    "date": meeting_date, "time": meeting_time,
                    "prospect": att_name, "type": meeting_type,
                    "prep_notes": meeting_details,
                })

            db.add_interaction({
                "prospect": att_name, "source": "calendar_event",
                "raw_text": json.dumps(data)[:2000],
                "summary": meeting_details,
            })
            db.add_activity({
                "prospect": att_name, "action": f"Calendar event: {meeting_type}",
                "outcome": subject, "next_step": "Prepare for meeting",
            })
            results.append(action)

    if not results:
        return f"Calendar event logged: {subject} (no attendees to track)"

    return f"Calendar event processed:\n" + "\n".join(f"  {r}" for r in results)


def _classify_meeting(subject: str, location: str, is_online: bool) -> str:
    """Classify a calendar event into a meeting type."""
    import re
    text = f" {subject} {location} ".lower()

    def _has_word(*words):
        return any(re.search(rf"\b{w}\b", text) for w in words)

    if _has_word("discovery", "intro", "initial", "first"):
        return "Discovery Call"
    if _has_word("review", "annual", "check-in", "checkin"):
        return "Review Meeting"
    if _has_word("presentation", "proposal") or "plan pres" in text:
        return "Plan Presentation"
    if _has_word("sign", "closing", "paperwork"):
        return "Closing"
    if _has_word("needs", "analysis") or "fact find" in text:
        return "Needs Analysis"
    if is_online or _has_word("teams", "zoom", "virtual", "call", "phone"):
        return "Call"
    return "Meeting"


def process_email_lead(data: dict) -> str:
    """Process a forwarded lead email from Zapier."""
    body = data.get("body", "")
    subject = data.get("subject", "")
    sender = data.get("from", "")

    if not body and not subject:
        return "Empty email payload — nothing to process."

    from pii import sanitize_for_prompt

    email_text = f"Subject: {subject}\nFrom: {sender}\n\n{body}"
    safe_email = sanitize_for_prompt(email_text[:3000])

    ctx = get_prompt_context()
    intro = build_advisor_intro()
    system_prompt = f"""You are a sales assistant for {ctx['advisor_first_name']}, {intro.split(', ', 1)[1] if ', ' in intro else 'a financial advisor'}.

Extract prospect information from the forwarded email/lead notification provided by the user.

Return a JSON object:
{{
  "name": "Full Name",
  "phone": "phone number if mentioned",
  "email": "email if mentioned",
  "product": "Insurance type or financial product they need",
  "notes": "Key details about the prospect",
  "priority": "Hot / Warm / Cold",
  "source": "Referral from [name]" or "{ctx['company']} Lead" or "Email Lead",
  "stage": "New Lead",
  "is_booking": true/false,
  "meeting_datetime": "ISO 8601 datetime string if a meeting/appointment was booked, otherwise null",
  "meeting_type": "Type of meeting (e.g. '1-Hour Online Meeting', 'Consultation') if booked, otherwise null",
  "event_action": "booked" or "cancelled" or "rescheduled" or null
}}

BOOKING DETECTION: If the email indicates that the prospect has ALREADY booked/scheduled a meeting or appointment (e.g. "booked a meeting", "scheduled an appointment", "reserved a time slot"), set is_booking to true, event_action to "booked", and extract the meeting details. If no meeting datetime is mentioned, set meeting_datetime to null but still set is_booking to true.

CANCELLATION DETECTION: If the email indicates a meeting/appointment was CANCELLED (e.g. "cancelled the meeting", "appointment cancelled"), set is_booking to true, event_action to "cancelled", and extract the prospect name. Include any reason in notes.

RESCHEDULE DETECTION: If the email indicates a meeting was RESCHEDULED (e.g. "rescheduled to", "moved the meeting"), set is_booking to true, event_action to "rescheduled", and set meeting_datetime to the NEW date/time.

Return ONLY valid JSON.

CRITICAL — DUPLICATE PREVENTION: A list of existing prospects/clients will be provided. If the person in the email matches or is likely the same person as an existing prospect (even if the spelling or name format differs slightly), you MUST use the EXACT name from the existing list. Only create a new name if there is clearly no match.
{build_anti_injection_warning()}"""

    existing_names = db.get_all_prospect_names()
    user_parts = []
    if existing_names:
        names_list = "\n".join(f"- {n}" for n in existing_names)
        user_parts.append(f"EXISTING PROSPECTS (use these exact names when a match is found):\n{names_list}")
    user_parts.append(f"EMAIL:\n{safe_email}")
    user_content = "\n\n".join(user_parts)

    try:
        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            max_completion_tokens=512,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content},
            ],
        )
        raw = response.choices[0].message.content.strip()

        if raw.startswith("```"):
            raw = raw.split("\n", 1)[1] if "\n" in raw else raw[3:]
            raw = raw.rstrip()
            if raw.endswith("```"):
                raw = raw[:-3].rstrip()
            raw = raw.strip()
            if raw.startswith("json"):
                raw = raw[4:].strip()

        prospect = json.loads(raw)
    except Exception as e:
        logger.error(f"AI extraction failed for email lead: {e}")
        return f"Could not parse lead email. Raw text saved for manual review.\n\nSubject: {subject}"

    name = prospect.get("name", "").strip()
    if not name:
        # Fall back to email or sender as name rather than losing all extracted data
        fallback_email = prospect.get("email", "").strip()
        if fallback_email:
            name = fallback_email.split("@")[0].replace(".", " ").title()
            prospect["name"] = name
            logger.info(f"Email lead: no name extracted, using email fallback '{name}'")
        elif sender:
            name = sender.split("@")[0].replace(".", " ").title() if "@" in sender else sender
            prospect["name"] = name
            logger.info(f"Email lead: no name extracted, using sender fallback '{name}'")
        else:
            return "Could not extract a prospect name from the email."

    existing = db.get_prospect_by_name(name)
    if existing:
        old_notes = existing.get("notes", "")
        new_notes = prospect.get("notes", "")
        combined = f"{old_notes} | [Email Lead] {new_notes}" if old_notes else f"[Email Lead] {new_notes}"
        updates = {"notes": combined}
        if prospect.get("email") and not existing.get("email"):
            updates["email"] = prospect["email"]
        if prospect.get("phone") and not existing.get("phone"):
            updates["phone"] = prospect["phone"]
        db.update_prospect(existing["name"], updates)
        result = f"Updated {existing['name']} with email lead details."
    else:
        db.add_prospect({
            "name": name,
            "phone": prospect.get("phone", ""),
            "email": prospect.get("email", ""),
            "source": prospect.get("source", "Email Lead"),
            "priority": prospect.get("priority", "Warm"),
            "stage": prospect.get("stage", "New Lead"),
            "product": prospect.get("product", ""),
            "notes": prospect.get("notes", ""),
        })
        result = f"New prospect: {name} — {prospect.get('product', '?')} ({prospect.get('source', 'Email Lead')})"

    db.add_interaction({
        "prospect": name, "source": "email_lead",
        "raw_text": email_text[:2000],
        "summary": prospect.get("notes", ""),
    })
    db.add_activity({
        "prospect": name, "action": "Lead intake (email)",
        "outcome": prospect.get("notes", ""),
        "next_step": "Initial contact",
    })

    if not existing:
        _score_and_schedule(name)

    # Extract client intelligence
    try:
        import memory_engine
        prospect_obj = db.get_prospect_by_name(name)
        if prospect_obj:
            memory_engine.extract_facts_from_interaction(
                prospect_name=prospect_obj["name"],
                prospect_id=prospect_obj["id"],
                interaction_text=body,
                source="email_lead",
            )
    except Exception:
        logger.exception("Memory extraction failed for email lead (non-blocking)")

    # Booking / cancellation / reschedule detection
    is_booking = prospect.get("is_booking", False)
    event_action = prospect.get("event_action") or ("booked" if is_booking else None)

    if event_action == "cancelled":
        # ── Cancellation: cancel meeting + stop nurture texts ──
        try:
            import booking_nurture
            prospect_obj = db.get_prospect_by_name(name)
            if prospect_obj:
                booking_nurture.cancel_sequence(prospect_obj["id"])
                # Mark the most recent scheduled meeting as cancelled
                all_meetings = db.read_meetings()
                for m in reversed(all_meetings):
                    if m.get("prospect", "").lower() == name.lower() and m.get("status", "Scheduled") != "Cancelled":
                        db.update_meeting(m["id"], {"status": "Cancelled"})
                        break
                logger.info("Email lead detected as cancellation — meeting + nurture cancelled for %s", name)
        except Exception:
            logger.exception("Cancellation handling failed for email lead (non-blocking)")

    elif event_action == "rescheduled" and is_booking:
        # ── Reschedule: cancel old nurture, create new meeting + new nurture sequence ──
        try:
            import booking_nurture
            prospect_obj = db.get_prospect_by_name(name)
            _phone = prospect.get("phone") or (prospect_obj or {}).get("phone", "")
            _pid = prospect_obj["id"] if prospect_obj else None
            meeting_datetime_str = prospect.get("meeting_datetime")
            meeting_type = prospect.get("meeting_type", "Consultation")

            if _pid:
                booking_nurture.cancel_sequence(_pid)

            if meeting_datetime_str and _phone:
                meeting_date, meeting_time = _parse_datetime(meeting_datetime_str)
                db.add_meeting({
                    "date": meeting_date, "time": meeting_time,
                    "prospect": name, "type": meeting_type,
                    "prep_notes": f"Rescheduled — {prospect.get('notes', '')}",
                })
                booking_nurture.create_sequence(
                    prospect_name=name,
                    prospect_id=_pid,
                    phone=_phone,
                    meeting_datetime_str=meeting_datetime_str,
                    meeting_date=meeting_date,
                    meeting_time=meeting_time,
                    meeting_type=meeting_type,
                    product=prospect.get("product", ""),
                )
                logger.info("Email lead detected as reschedule — new nurture sequence created for %s", name)
        except Exception:
            logger.exception("Reschedule handling failed for email lead (non-blocking)")

    elif is_booking:
        # ── New booking: create meeting + trigger nurture sequence ──
        try:
            prospect_obj = db.get_prospect_by_name(name)
            _phone = prospect.get("phone") or (prospect_obj or {}).get("phone", "")
            _pid = prospect_obj["id"] if prospect_obj else None
            meeting_datetime_str = prospect.get("meeting_datetime")
            meeting_type = prospect.get("meeting_type", "Consultation")

            if meeting_datetime_str:
                meeting_date, meeting_time = _parse_datetime(meeting_datetime_str)
                db.add_meeting({
                    "date": meeting_date, "time": meeting_time,
                    "prospect": name, "type": meeting_type,
                    "prep_notes": prospect.get("notes", ""),
                })

                if _phone:
                    import booking_nurture
                    booking_nurture.create_sequence(
                        prospect_name=name,
                        prospect_id=_pid,
                        phone=_phone,
                        meeting_datetime_str=meeting_datetime_str,
                        meeting_date=meeting_date,
                        meeting_time=meeting_time,
                        meeting_type=meeting_type,
                        product=prospect.get("product", ""),
                    )
                    logger.info("Email lead detected as booking — nurture sequence created for %s", name)
                else:
                    logger.warning("Email lead detected as booking but no phone on file — nurture skipped for %s", name)
            elif _phone:
                # Booking detected but no datetime — draft a thank-you SMS instead
                context = f"Booked a meeting: {prospect.get('product', 'general inquiry')}"
                if prospect.get("notes"):
                    context += f" — {prospect['notes'][:100]}"
                _draft_booking_thanks_sms(name, _phone, context, _pid)
        except Exception:
            logger.exception("Booking nurture setup failed for email lead (non-blocking)")

    elif not existing and prospect.get("phone"):
        # Speed-to-lead: instant welcome SMS draft for new leads with a phone number
        try:
            prospect_obj = db.get_prospect_by_name(name)
            context = f"Email lead: {prospect.get('product', 'general inquiry')}"
            if prospect.get("notes"):
                context += f" — {prospect['notes'][:100]}"
            _draft_welcome_sms(name, prospect["phone"], context, prospect_obj["id"] if prospect_obj else None)
        except Exception:
            logger.exception("Welcome SMS draft failed for email lead (non-blocking)")

    return result


def _score_and_schedule(name: str):
    """Score a newly created prospect and set their first follow-up date."""
    import scoring
    from datetime import timedelta

    prospect = db.get_prospect_by_name(name)
    if not prospect:
        return

    score_data = scoring.score_prospect(prospect)
    score = score_data.get("score", 0)

    if score >= 70:
        priority = "Hot"
    elif score >= 40:
        priority = "Warm"
    else:
        priority = "Cold"

    days = {"Hot": 1, "Warm": 2, "Cold": 5}.get(priority, 3)
    next_followup = (datetime.now() + timedelta(days=days)).strftime("%Y-%m-%d")

    db.update_prospect(name, {"priority": priority, "next_followup": next_followup})
    logger.info(f"Scored {name}: {score}/100 ({priority}), follow-up {next_followup}")


def get_welcome_sms_prompt(tenant_id=1):
    ctx = get_prompt_context(tenant_id)
    intro = build_advisor_intro(tenant_id)
    first = ctx["advisor_first_name"]
    company = ctx["company"]
    sig = ctx["sender_signature"]
    return f"""You are writing a first-contact text message for {intro}.

This person just reached out (via a website form or email) and {first} wants to text them quickly while they're still thinking about it.

RULES:
1. 1-2 sentences ONLY
2. First name only, no last name
3. Sign off with "{sig}"
4. Acknowledge how they connected (website, email, etc.) — keep it natural
5. Low-pressure ask: worth a quick 15 min chat this week?
6. Always identify as "{first} from {company}"
7. Never mention specific financial products, rates, or numbers
8. Never make financial promises or return guarantees

If context about what they're interested in is provided, weave a subtle reference to it — but never mention specific products or numbers.

If no prospect first name is provided, simply omit the name from the greeting.

VOICE:
Real person, real phone. Short. Direct. Feels like a human who saw their message and picked up the phone.

Good examples:
- "Hey Sarah, {first} from {company} here — saw your message come through and wanted to reach out. Worth a quick chat this week? {sig}"
- "Hey, {first} from {company} — got your info and wanted to connect. Do you have 15 min this week? {sig}"

Write ONLY the message text.
{build_anti_injection_warning()}"""


def _draft_welcome_sms(prospect_name: str, phone: str, source_context: str, prospect_id=None):
    """Generate an instant welcome SMS draft for a new lead and queue for approval."""
    import approval_queue as aq
    import sms_sender
    from pii import RedactionContext, sanitize_for_prompt

    normalized = sms_sender._normalize_phone(phone)
    first_name = prospect_name.split()[0] if prospect_name else ""
    has_real_name = bool(first_name) and not first_name.startswith("Contact")

    redact_names = [prospect_name] if has_real_name and prospect_name else []
    with RedactionContext(prospect_names=redact_names) as pii_ctx:
        name_line = f"Prospect first name: {first_name}" if has_real_name else "Prospect first name: (not provided)"
        user_content = pii_ctx.redact(sanitize_for_prompt(
            f"{name_line}\nHow they connected: {source_context}"
        ))

        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {"role": "system", "content": get_welcome_sms_prompt()},
                {"role": "user", "content": user_content},
            ],
            max_completion_tokens=150,
            temperature=0.7,
        )
        content = pii_ctx.restore(response.choices[0].message.content.strip())

    if has_real_name and first_name != prospect_name:
        content = content.replace(prospect_name, first_name)

    draft = aq.add_draft(
        draft_type="welcome_sms",
        channel="sms_draft",
        content=content,
        context=f"Speed-to-lead welcome SMS for {prospect_name or phone} ({normalized})",
        prospect_id=prospect_id,
    )

    # Send to Telegram for approval
    try:
        import asyncio
        import sys
        from telegram import InlineKeyboardButton, InlineKeyboardMarkup

        main_mod = sys.modules.get("__main__")
        telegram_app = getattr(main_mod, "telegram_app", None)
        bot_event_loop = getattr(main_mod, "bot_event_loop", None)
        chat_id = os.environ.get("TELEGRAM_CHAT_ID", "")
        bot_instance = getattr(telegram_app, "bot", None) if telegram_app else None

        if bot_instance and chat_id and bot_event_loop and bot_event_loop.is_running():
            keyboard = InlineKeyboardMarkup([[
                InlineKeyboardButton("Send", callback_data=f"draft_approve_{draft['id']}"),
                InlineKeyboardButton("Skip", callback_data=f"draft_dismiss_{draft['id']}"),
            ]])
            display = prospect_name or phone
            text = (
                f"⚡ NEW LEAD — {display}\n"
                f"{source_context}\n\n"
                f"{content}"
            )

            async def send():
                msg = await bot_instance.send_message(chat_id=chat_id, text=text, reply_markup=keyboard)
                aq.set_telegram_message_id(draft["id"], str(msg.message_id))

            asyncio.run_coroutine_threadsafe(send(), bot_event_loop)
    except Exception:
        logger.exception("Could not send welcome SMS draft to Telegram")

    logger.info("Welcome SMS draft queued for %s (%s)", prospect_name, normalized)
    return draft


def get_booking_thanks_sms_prompt(tenant_id=1):
    ctx = get_prompt_context(tenant_id)
    intro = build_advisor_intro(tenant_id)
    first = ctx["advisor_first_name"]
    company = ctx["company"]
    sig = ctx["sender_signature"]
    return f"""You are writing a text message for {intro}.

This person just BOOKED a meeting with {first}. They've already committed — do NOT ask them to book or chat. Instead, thank them and confirm.

RULES:
1. 1-2 sentences ONLY
2. First name only, no last name
3. Sign off with "{sig}"
4. Thank them for booking
5. Express that you're looking forward to the meeting
6. Always identify as "{first} from {company}"
7. Never mention specific financial products, rates, or numbers
8. Never make financial promises or return guarantees

If context about what they're interested in is provided, weave a subtle reference — but never mention specific products or numbers.

If no prospect first name is provided, simply omit the name from the greeting.

VOICE:
Real person, real phone. Short. Direct. Feels like a human who saw the booking and wanted to say thanks.

Good examples:
- "Hey Sarah, {first} from {company} here — thanks for booking in, looking forward to chatting with you! {sig}"
- "Hey, {first} from {company} — saw the booking come through, appreciate you setting that up. Talk soon! {sig}"

Write ONLY the message text.
{build_anti_injection_warning()}"""


def _draft_booking_thanks_sms(prospect_name: str, phone: str, source_context: str, prospect_id=None):
    """Generate a thank-you SMS draft for a prospect who booked a meeting, and queue for approval."""
    import approval_queue as aq
    import sms_sender
    from pii import RedactionContext, sanitize_for_prompt

    normalized = sms_sender._normalize_phone(phone)
    first_name = prospect_name.split()[0] if prospect_name else ""
    has_real_name = bool(first_name) and not first_name.startswith("Contact")

    redact_names = [prospect_name] if has_real_name and prospect_name else []
    with RedactionContext(prospect_names=redact_names) as pii_ctx:
        name_line = f"Prospect first name: {first_name}" if has_real_name else "Prospect first name: (not provided)"
        user_content = pii_ctx.redact(sanitize_for_prompt(
            f"{name_line}\nBooking context: {source_context}"
        ))

        response = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {"role": "system", "content": get_booking_thanks_sms_prompt()},
                {"role": "user", "content": user_content},
            ],
            max_completion_tokens=150,
            temperature=0.7,
        )
        content = pii_ctx.restore(response.choices[0].message.content.strip())

    if has_real_name and first_name != prospect_name:
        content = content.replace(prospect_name, first_name)

    draft = aq.add_draft(
        draft_type="welcome_sms",
        channel="sms_draft",
        content=content,
        context=f"Booking thank-you SMS for {prospect_name or phone} ({normalized})",
        prospect_id=prospect_id,
    )

    # Send to Telegram for approval
    try:
        import asyncio
        import sys
        from telegram import InlineKeyboardButton, InlineKeyboardMarkup

        main_mod = sys.modules.get("__main__")
        telegram_app = getattr(main_mod, "telegram_app", None)
        bot_event_loop = getattr(main_mod, "bot_event_loop", None)
        chat_id = os.environ.get("TELEGRAM_CHAT_ID", "")
        bot_instance = getattr(telegram_app, "bot", None) if telegram_app else None

        if bot_instance and chat_id and bot_event_loop and bot_event_loop.is_running():
            keyboard = InlineKeyboardMarkup([[
                InlineKeyboardButton("Send", callback_data=f"draft_approve_{draft['id']}"),
                InlineKeyboardButton("Skip", callback_data=f"draft_dismiss_{draft['id']}"),
            ]])
            display = prospect_name or phone
            text = (
                f"📅 BOOKING CONFIRMED — {display}\n"
                f"{source_context}\n\n"
                f"{content}"
            )

            async def send():
                msg = await bot_instance.send_message(chat_id=chat_id, text=text, reply_markup=keyboard)
                aq.set_telegram_message_id(draft["id"], str(msg.message_id))

            asyncio.run_coroutine_threadsafe(send(), bot_event_loop)
    except Exception:
        logger.exception("Could not send booking thanks SMS draft to Telegram")

    logger.info("Booking thanks SMS draft queued for %s (%s)", prospect_name, normalized)
    return draft


def _parse_datetime(dt_str: str) -> tuple[str, str]:
    """Parse an ISO datetime string into (date, time) strings."""
    try:
        dt = datetime.fromisoformat(dt_str.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d"), dt.strftime("%I:%M %p")
    except (ValueError, AttributeError):
        return dt_str[:10] if len(dt_str) >= 10 else "", ""


def _guess_product(service: str, notes: str) -> str:
    """Guess the insurance product from booking service name and notes."""
    text = f"{service} {notes}".lower()
    if "life" in text:
        return "Life Insurance"
    if "disab" in text:
        return "Disability Insurance"
    if "home" in text or "house" in text or "property" in text:
        return "Home Insurance"
    if "auto" in text or "car" in text or "vehicle" in text:
        return "Auto Insurance"
    if "commercial" in text or "business" in text:
        return "Commercial Insurance"
    if "wealth" in text or "invest" in text or "rrsp" in text or "tfsa" in text:
        return "Wealth Management"
    return ""


# ---------------------------------------------------------------------------
# Website lead intake
# ---------------------------------------------------------------------------

PRIORITY_RANK = {"Hot": 3, "Warm": 2, "Cool": 1, "Cold": 0}

# Map calmmoney.ca service dropdown values to CRM product options
_SERVICE_TO_PRODUCT = {
    "retirement planning": "Wealth Management",
    "investment management": "Wealth Management",
    "wealth management": "Wealth Management",
    "life insurance": "Life Insurance",
    "estate planning": "Estate Planning",
    "disability insurance": "Disability Insurance",
    "critical illness": "Critical Illness",
    "group benefits": "Group Benefits",
    "tax planning": "Wealth Management",
    "corporate financial planning": "Wealth Management",
}


def _dedup_or_create(email: str, name: str, data: dict) -> tuple:
    """Check for existing prospect by email. Returns (prospect_dict, is_new)."""
    existing = db.get_prospect_by_email(email) if email else None

    if existing:
        updates = {}
        # Upgrade placeholder name if real name provided
        if name and (not existing.get("name") or existing["name"] == email.split("@")[0]):
            updates["name"] = name
        if data.get("phone") and not existing.get("phone"):
            updates["phone"] = data["phone"]
        if data.get("product") and not existing.get("product"):
            updates["product"] = data["product"]
        # Bump priority if higher
        new_priority = data.get("priority", "")
        if PRIORITY_RANK.get(new_priority, 0) > PRIORITY_RANK.get(existing.get("priority", ""), 0):
            updates["priority"] = new_priority
        # Append to notes
        note_addition = data.get("note_addition", "")
        if note_addition:
            old_notes = existing.get("notes", "")
            updates["notes"] = f"{old_notes} | {note_addition}" if old_notes else note_addition

        if updates:
            db.update_prospect(existing["name"], updates)
        updated = db.get_prospect_by_email(email) or existing
        return updated, False
    else:
        prospect_name = name or (email.split("@")[0] if email else "Unknown")
        db.add_prospect({
            "name": prospect_name,
            "email": email,
            "phone": data.get("phone", ""),
            "source": "website",
            "priority": data.get("priority", "Warm"),
            "stage": "New Lead",
            "product": data.get("product", ""),
            "notes": data.get("note_addition", ""),
            "send_channel": "resend",
        })
        new_prospect = db.get_prospect_by_email(email) or db.get_prospect_by_name(prospect_name)
        return new_prospect, True


def process_website_contact(data: dict) -> str:
    """Process a contact form submission from calmmoney.ca."""
    name = (data.get("name") or "").strip()
    email = (data.get("email") or "").strip()
    phone = (data.get("phone") or "").strip()
    service = (data.get("service") or "").strip()
    message = (data.get("message") or "").strip()

    note = f"[Website Contact] Service: {service}"
    if message:
        note += f" | {message[:200]}"

    product = _SERVICE_TO_PRODUCT.get(service.lower(), service) if service else ""

    prospect, is_new = _dedup_or_create(email, name, {
        "phone": phone,
        "product": product,
        "priority": "Hot",
        "note_addition": note,
    })

    prospect_name = prospect["name"] if prospect else name or email

    db.add_interaction({
        "prospect": prospect_name,
        "source": "website_contact",
        "raw_text": f"Service: {service}\nMessage: {message}",
        "summary": note,
    })

    if is_new:
        db.add_activity({
            "prospect": prospect_name,
            "action": "Website contact form submitted",
            "outcome": note,
            "next_step": "Follow up within 24 hours",
        })
        # Priority is explicitly set to Hot for contact form leads; schedule follow-up
        # without re-scoring (which could downgrade the priority).
        from datetime import timedelta
        next_followup = (datetime.now() + timedelta(days=1)).strftime("%Y-%m-%d")
        db.update_prospect(prospect_name, {"next_followup": next_followup})

    # Auto-generate follow-up draft for new Hot website leads
    if is_new and prospect:
        try:
            import follow_up
            activity_summary = f"Website contact form: {service}"
            if message:
                activity_summary += f" — {message[:150]}"
            follow_up.generate_follow_up_draft(
                prospect_name=prospect_name,
                activity_summary=activity_summary,
                activity_type="website_contact",
            )
        except Exception:
            logger.exception("Follow-up draft generation failed for website contact (non-blocking)")

    # Speed-to-lead: instant welcome SMS draft for new leads with a phone number
    if is_new and phone and prospect:
        try:
            context = f"Website contact: {service}"
            if message:
                context += f" — {message[:100]}"
            _draft_welcome_sms(prospect_name, phone, context, prospect.get("id"))
        except Exception:
            logger.exception("Welcome SMS draft failed for website contact (non-blocking)")

    action = "New website lead" if is_new else "Updated"
    return f"{action}: {prospect_name} — {service} (Hot, website contact)"


def process_website_quiz(data: dict) -> str:
    """Process a retirement quiz submission from calmmoney.ca."""
    email = (data.get("email") or "").strip()
    score = data.get("score", 0)
    tier = data.get("tier", "")
    answers = data.get("answers", [])

    note = f"[Website Quiz] Score: {score}/100, Tier: {tier}"
    if answers:
        weak = [a["optionLabel"] for a in answers if a.get("points", 0) <= 10]
        if weak:
            note += f" | Weak areas: {', '.join(weak[:3])}"

    prospect, is_new = _dedup_or_create(email, "", {
        "priority": "Warm",
        "note_addition": note,
    })

    prospect_name = prospect["name"] if prospect else email.split("@")[0]
    prospect_id = prospect["id"] if prospect else None

    # Store score in client memory
    if prospect_id:
        try:
            import memory_engine
            memory_engine.extract_facts_from_interaction(
                prospect_name=prospect_name,
                prospect_id=prospect_id,
                interaction_text=f"Retirement quiz: scored {score}/100 ({tier}). {note}",
                source="website_quiz",
            )
        except Exception:
            logger.exception("Memory extraction failed for quiz (non-blocking)")

    # Start nurture sequence for new quiz leads
    if is_new and prospect_id:
        try:
            import nurture
            nurture.create_sequence(prospect_name=prospect_name, prospect_id=prospect_id)
        except Exception:
            logger.exception("Nurture sequence creation failed (non-blocking)")

    action = "New quiz lead" if is_new else "Updated"
    return f"{action}: {prospect_name} — Score {score}/100 (Warm, website quiz)"


def process_website_tool(data: dict) -> str:
    """Process a tool capture form from calmmoney.ca."""
    email = (data.get("email") or "").strip()
    tool_name = (data.get("toolName") or data.get("tool_name") or "").strip()

    note = f"[Website Tool] Used: {tool_name}"

    prospect, is_new = _dedup_or_create(email, "", {
        "priority": "Cool",
        "note_addition": note,
    })

    prospect_name = prospect["name"] if prospect else email.split("@")[0]

    action = "New tool lead" if is_new else "Updated"
    return f"{action}: {prospect_name} — {tool_name} (Cool, website tool)"


def process_email_event(data: dict) -> str:
    """Process a Resend engagement event (open/click/bounce/complaint)."""
    event_type = (data.get("event_type") or "").strip()
    email = (data.get("email") or "").strip()
    resend_email_id = (data.get("resend_email_id") or "").strip()

    if not event_type or not email:
        return "Missing event_type or email in email_event payload."

    import analytics

    # Try to find matching outcome by resend_email_id first
    outcome = None
    if resend_email_id:
        with db.get_db() as conn:
            row = conn.execute(
                "SELECT * FROM outcomes WHERE resend_email_id = ?",
                (resend_email_id,),
            ).fetchone()
            if row:
                outcome = dict(row)

    # Fallback: match by prospect email + recent sent_at
    if not outcome:
        prospect = db.get_prospect_by_email(email)
        if prospect:
            with db.get_db() as conn:
                row = conn.execute(
                    """SELECT o.* FROM outcomes o
                       WHERE o.target = ? AND o.sent_at >= date('now', '-2 days')
                       ORDER BY o.created_at DESC LIMIT 1""",
                    (prospect["name"],),
                ).fetchone()
                if row:
                    outcome = dict(row)

    if event_type == "email.opened" and outcome:
        analytics.update_outcome(outcome["id"], response_received=True)
        return f"Email opened by {email} — outcome #{outcome['id']} updated"

    elif event_type == "email.clicked" and outcome:
        analytics.update_outcome(outcome["id"], response_received=True, response_type="clicked")
        return f"Email link clicked by {email} — outcome #{outcome['id']} updated"

    elif event_type == "email.bounced":
        prospect = db.get_prospect_by_email(email)
        if prospect:
            db.update_prospect(prospect["name"], {"notes": f"{prospect.get('notes', '')} | [BOUNCED] Email bounced"})
            try:
                with db.get_db() as conn:
                    conn.execute(
                        "UPDATE nurture_sequences SET status = 'paused' WHERE prospect_name = ? AND status = 'active'",
                        (prospect["name"],),
                    )
            except Exception:
                logger.exception("Failed to pause nurture for bounced email")
        return f"Email bounced for {email}"

    elif event_type == "email.complained":
        prospect = db.get_prospect_by_email(email)
        if prospect:
            db.update_prospect(prospect["name"], {
                "notes": f"{prospect.get('notes', '')} | [COMPLAINT] Spam complaint — all outreach paused",
                "stage": "Do Not Contact",
            })
            try:
                with db.get_db() as conn:
                    conn.execute(
                        "UPDATE nurture_sequences SET status = 'paused' WHERE prospect_name = ? AND status = 'active'",
                        (prospect["name"],),
                    )
            except Exception:
                logger.exception("Failed to pause nurture for complaint")
        return f"Spam complaint from {email} — outreach paused"

    if outcome:
        return f"Event {event_type} for {email} — outcome #{outcome['id']} (no action taken)"
    return f"Event {event_type} for {email} — no matching outcome found (ignored)"
